name: Build and Package

on:
  push:
    branches:
      - main

jobs:
  build_and_pack:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ vars.DOTNET_VERSION }}

      - name: Get Project Version
        id: get_version
        uses: mod-posh/GetProjectVersion@main
        with:
          Filename: 'Directory.Build.props'
          verbose: "verbose"
      - name: Compose preview version parts
        shell: pwsh
        run: |
          $sha7 = "${env:GITHUB_SHA}".Substring(0,7)
          echo "VERSION_PREFIX=${{ steps.get_version.outputs.version }}" >> $env:GITHUB_ENV
          echo "VERSION_SUFFIX=preview.${env:GITHUB_RUN_NUMBER}-g$sha7" >> $env:GITHUB_ENV

      - name: Clean
        run: dotnet clean ${{ github.workspace }}/${{ vars.PROJECT_NAME }}/${{ vars.PROJECT_NAME }}.sln --configuration Release
      - name: Restore dependencies
        run: dotnet restore ${{ github.workspace }}/${{ vars.PROJECT_NAME }}/${{ vars.PROJECT_NAME }}.sln
      - name: Build
        run: dotnet build ${{ github.workspace }}/${{ vars.PROJECT_NAME }}/${{ vars.PROJECT_NAME }}.sln --configuration Release --no-restore -p:ContinuousIntegrationBuild=true
      - name: Package
        run: >
          dotnet pack ${{ github.workspace }}/${{ vars.PROJECT_NAME }}/${{ vars.PROJECT_NAME }}.sln
          --configuration Release
          --output nupkgs
          --no-build
          -p:ContinuousIntegrationBuild=true
          -p:VersionPrefix=${{ env.VERSION_PREFIX }}
          -p:VersionSuffix=${{ env.VERSION_SUFFIX }}

      - name: Push to NuGet
        run: dotnet nuget push ./publish/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
